project_id = "umyjqvmpvjfikljhoofy"

[functions.auto-complete-jobs]
verify_jwt = false

[functions.generate-facility-contract]
verify_jwt = false

[functions.generate-interpreter-contract]
verify_jwt = false

[functions.generate-invoice-pdf]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.send-invoice-email]
verify_jwt = false
